Створення одновимірного масиву з першими 10 натуральними числами та виведення їх значень:

In [6]:
import numpy as np
one_dimensional_array = list(range(1, 11))
print(one_dimensional_array)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Створення двовимірного масиву розміром 3x3, заповненого нулями, та виведення його значень:

In [7]:

two_dimensional_array = np.zeros((3, 3))
print(two_dimensional_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Створення масиву розміром 5x5 з випадковими цілими числами від 1 до 10 та виведення його значень:

In [8]:


random_array = np.random.randint(1, 11, (5, 5))
print(random_array)


[[ 1  6  5  1  9]
 [ 3  9 10  3  8]
 [ 6  9  8  1  9]
 [ 5  7  5  6  8]
 [ 7  7  1 10  4]]


Cтворення масиву розміром 4x4 з випадковими дійсними числами від 0 до 1 та виведення його значень:

In [9]:


random_float_array = np.random.rand(4, 4)
print(random_float_array)


[[0.20275409 0.37024087 0.07247702 0.25566389]
 [0.05999505 0.93393026 0.81112444 0.97728858]
 [0.91048635 0.97503806 0.22496123 0.39300118]
 [0.59670233 0.40231755 0.93336247 0.97528781]]


Створення двох одновимірних масивів розміром 5 з випадковими цілими числами від 1 до 10 та виконання поелементних операцій додавання, віднімання та множення:

In [10]:


array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

print("Addition:", addition_result)
print("Subtraction:", subtraction_result)
print("Multiplication:", multiplication_result)


Addition: [ 9  8  7 10 11]
Subtraction: [-1 -2  5  2 -5]
Multiplication: [20 15  6 24 24]


Створення двох векторів розміром 7 з довільними числами та знаходження їх скалярного добутку:

In [11]:


vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

dot_product = np.dot(vector1, vector2)
print("Scalar Dot Product:", dot_product)


Scalar Dot Product: 1.8150783582738677


Створення двох матриць розміром 2x2 та 2x3, заповнення їх випадковими цілими числами від 1 до 10 та перемноження їх:

In [12]:


matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))

result = np.dot(matrix1, matrix2)
print(result)


[[ 99 171 117]
 [ 15  28  20]]


Створення матриці розміром 3x3, заповнення її випадковими цілими числами від 1 до 10 та знаходження її оберненої матриці (при умові, що матриця є оборотною):

In [13]:


matrix = np.random.randint(1, 11, (3, 3))

try:
    inverse_matrix = np.linalg.inv(matrix)
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Matrix is not invertible.")


[[ 0.55223881  0.07462687 -0.64179104]
 [-0.10447761 -0.14925373  0.28358209]
 [-0.07462687  0.17910448  0.05970149]]


Створення матриці розміром 4x4 з випадковими дійсними числами від 0 до 1 та транспонування її:

In [14]:


matrix = np.random.rand(4, 4)
transposed_matrix = matrix.T
print(transposed_matrix)


[[0.50300033 0.69830992 0.9833733  0.13113397]
 [0.38702969 0.71827889 0.05172286 0.08062171]
 [0.90690359 0.28439669 0.73495466 0.54666549]
 [0.79852659 0.23493433 0.37943166 0.93882929]]


Створення матриці розміром 3x4 та вектору розміром 4, заповнення їх випадковими цілими числами від 1 до 10 та перемноження матриці на вектор:

In [15]:


matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, 4)

result = np.dot(matrix, vector)
print(result)


[198 118 189]


Створення матриці розміром 2x3 та вектору розміром 3, заповнення їх випадковими дійсними числами від 0 до 1 та перемноження матриці на вектор:

In [16]:


matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

result = np.dot(matrix, vector)
print(result)


[0.07973761 0.1444209 ]


Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами від 1 до 10 та виконання поелементного множення:

In [17]:


matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

elementwise_product = np.multiply(matrix1, matrix2)
print(elementwise_product)


[[ 6 20]
 [30  7]]


Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами від 1 до 10 та знаходження їх добутку:

In [18]:


matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

matrix_product = np.dot(matrix1, matrix2)
print(matrix_product)


[[84 84]
 [65 70]]


Створення матриці розміром 5x5, заповнення її випадковими цілими числами від 1 до 100 та знаходження суми елементів матриці:

In [19]:


matrix = np.random.randint(1, 101, (5, 5))
matrix_sum = np.sum(matrix)
print("Матриця:\n", matrix)
print("Сума елементів матриці:", matrix_sum)


Матриця:
 [[78 15 51 84 62]
 [59 77 65 87 25]
 [16 92 81 92 78]
 [65 96 27 85 79]
 [ 4 86 59 10 25]]
Сума елементів матриці: 1498


Створення двох матриць розміром 4x4, заповнення їх випадковими цілими числами від 1 до 10 та знаходження їх різниці:

In [20]:


matrix1 = np.random.randint(1, 11, (4, 4))
matrix2 = np.random.randint(1, 11, (4, 4))

matrix_difference = matrix1 - matrix2
print(matrix_difference)


[[ 3  5 -1 -3]
 [-3 -5  2 -5]
 [ 4  1  9 -3]
 [-4 -4  0  0]]


Створення матриці розміром 3x3, заповнення її випадковими дійсними числами від 0 до 1 та знаходження вектора-стовпчика, що містить суму елементів кожного рядка матриці:


In [23]:

matrix = np.random.rand(3, 3)
row_sums = matrix.sum(axis=1)
column_vector = row_sums.reshape(3, 1)
print(column_vector)


[[1.83298994]
 [1.74662361]
 [1.30549248]]


Створення матриці розміром 3x4 з довільними цілими числами та створення матриці з квадратами цих чисел:

In [24]:

matrix = np.random.randint(1, 101, (3, 4))
squared_matrix = np.square(matrix)
print("Оригінальна матриця:\n", matrix)
print("Матриця з квадратами чисел:\n", squared_matrix)


Оригінальна матриця:
 [[ 74  29  39  85]
 [100   9  25  89]
 [  9  88  91  38]]
Матриця з квадратами чисел:
 [[ 5476   841  1521  7225]
 [10000    81   625  7921]
 [   81  7744  8281  1444]]


Створення вектора розміром 4, заповненого випадковими цілими числами в діапазоні від 1 до 50 та знаходження вектора з квадратними коренями цих чисел:

In [25]:

vector = np.random.randint(1, 51, 4)
square_root_vector = np.sqrt(vector)
print("Оригінальний вектор:\n", vector)
print("Вектор з квадратними коренями:\n", square_root_vector)


Оригінальний вектор:
 [38 38 22 32]
Вектор з квадратними коренями:
 [6.164414   6.164414   4.69041576 5.65685425]
